# Generated by Django 4.1.2 on 2022-11-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
