# Generated by Django 4.1.2 on 2022-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='viewed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
